name: Go

on: 
  push:
    tags:
    - '*'
  
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu -y
        CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -o rssbot .
        
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "rssbot"
        bodyFile: ""
        token: ${{ secrets.GITHUB_TOKEN }}